server:
  port: 9000

spring:
  application:
    name: cards
  profiles:
    active:
    - prod
  datasource:
    url: jdbc:mysql://localhost:3309/cards
    username: root
    password: Rohit@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  sql:
   init:
    mode: always
    generate-ddl: true
    properties:
      hibernate:
       ddl-auto: update
#  config:
#   import:
#   - "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"