services:
 accounts:
  image: "rohitgavande/accounts"
  container_name : accounts_ms
  ports:
  - "8080:8080"
  deploy:
   resources:
    limits:
     memory: 700m
  networks: 
   - eazybank
 loans:
  image: "rohitgavande/loans:v1"
  container_name : Loans_ms
  ports:
   - "8090:8090"
  deploy:
   resources:
    limits:
     memory: 700m
  networks: 
   - eazybank
 cards:
  image: "rohitgavande/cards:v1"
  container_name : cards_ms
  ports:
  - "9000:9000"
  deploy:
   resources:
    limits:
     memory: 700m
  networks: 
   - eazybank
networks:
 eazybank:
  driver: "bridge"


