server:
  port: 8090

spring:
  application:
    name: loans
  profiles:
    active:
    - prod 
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: Rohit@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
       ddl-auto: update
  config:
   import:
   - "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"