server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active:
#    - native
    - git
  cloud:
    config:
      server:
#        native:
#          search-locations:
#          - "classpath:/config"
       git:
        uri: "https://github.com/rohitgavande/microService-config"
        default-label: main
        timeout: 5
        clone-on-start: true
        force-pull: true

encrypt:
  key: "12345"
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true