server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active:
#    - native
    - git
  cloud:
    config:
      server:
#        native:
#          search-locations:
#          - "classpath:/config"
       git:
        uri: "https://github.com/rohitgavande/microService-config"
        default-label: main
        timeout: 5
        clone-on-start: true
        force-pull: true

encrypt:
  key: "12345"
