server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: Rohit@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
       ddl-auto: update
  profiles:
    active:
    - prod
  config:
    import:
    - "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
