server:
  port: 8080

spring:
  application:
    name: accounts
#  datasource:
#    url: jdbc:mysql://localhost:3307/accountsdb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  sql:
   init:
    mode: always
#    generate-ddl: true
#    properties:
#      hibernate:
#       ddl-auto: update
  profiles:
    active:
    - prod
  config:
    import:
    - "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
   prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
   name: "accounts"
   description: "EazyBank accounts application"
