server:
  port: 8080

spring:
  application:
    name: Accounts-Service
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank
    username: root
    password: Rohit@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
       ddl-auto: update
  profiles:
    active:
    - "prod"
build:
 version: "1.0"
 
accounts:
 message: "Welcome to Eazybank Account related local API's"
 ContactDetails:
  name: "Rohit- Developer"
  email: "Rohit@gmail.com"
 OnCallSupport:
  -1234567892
  -5846541254
 